"""
Generate APArchipelagoIdMappings.reds from this world's locations.py / items.py.

The Cyberpunk 2077 mod calls APNativeMappings.ResolveLocationAddress(String)
and APNativeMappings.ResolveItemId(Int64) to translate between Archipelago
wire identifiers and the internal "ap_*" / quest-style strings the game uses.

That mapping is derived from the world's data tables (locations.py and items.py).
Since the table codes are auto-assigned sequentially at module load, the only
reliable way to keep RedScript in sync is to emit it from the same Python source.

Usage
-----
    python -m worlds.cyberpunk2077.tools.generate_redscript_ap_mappings \
        --output path/to/APArchipelagoIdMappings.reds

If --output is omitted the script tries to write to the mod-repo at:
    <mod-root>/Cyberpunk2077/r6/scripts/CyberPunkArchipelago/
        Cyberpunk2077_Archipelago_Client/APArchipelagoIdMappings.reds

The mod-root is resolved via $CYBERPUNK_MOD_ROOT or by walking up from this
file (resolving junctions/symlinks). The repository ships a wrapper at
``tools/build_cyberpunk2077_apworld.py`` that always passes an explicit
--output and runs this generator before invoking Archipelago's
"Build APWorlds" launcher component.
"""

from __future__ import annotations

import argparse
import datetime
import os
import sys
from pathlib import Path
from typing import Dict, Iterable, List, Tuple


THIS_FILE = Path(__file__).resolve()
WORLD_DIR = THIS_FILE.parent.parent


def _load_world_modules():
    """Import locations + items from the cyberpunk2077 world package.

    Works whether the script is run as ``python -m worlds.cyberpunk2077.tools...``
    from the Archipelago source root, or as a plain script from anywhere as long
    as ARCHIPELAGO_ROOT is set (or an Archipelago checkout sits beside the mod).
    """
    try:
        from worlds.cyberpunk2077 import locations as locations_mod  # type: ignore
        from worlds.cyberpunk2077 import items as items_mod  # type: ignore
        return locations_mod, items_mod
    except ImportError:
        pass

    ap_root = os.environ.get("ARCHIPELAGO_ROOT")
    candidates: List[Path] = []
    if ap_root:
        candidates.append(Path(ap_root))
    # Walk up from this file looking for a sibling Archipelago checkout.
    for parent in [WORLD_DIR.parent.parent, *WORLD_DIR.parents]:
        candidates.append(parent.parent / "Archipelago")
        candidates.append(parent / "Archipelago")

    for candidate in candidates:
        if candidate.is_dir() and (candidate / "BaseClasses.py").is_file():
            sys.path.insert(0, str(candidate))
            try:
                from worlds.cyberpunk2077 import locations as locations_mod  # type: ignore
                from worlds.cyberpunk2077 import items as items_mod  # type: ignore
                return locations_mod, items_mod
            except ImportError:
                sys.path.remove(str(candidate))
                continue

    raise ImportError(
        "Could not import worlds.cyberpunk2077.locations / .items.\n"
        "Set ARCHIPELAGO_ROOT to the Archipelago source folder, or run via\n"
        "    python -m worlds.cyberpunk2077.tools.generate_redscript_ap_mappings\n"
        "from the Archipelago source root."
    )


def build_location_mapping(locations_mod) -> Dict[str, int]:
    """Return ``{internal_check_string: archipelago_wire_id}``.

    Mirrors the same resolution order the client uses today (see
    APQuestLocationLookup + the manual entries appended to
    ``location_internal_id_to_display_name``):

    1. ``location_internal_id_to_display_name`` already contains every entry
       in ``location_table`` plus the manual aliases (lifepath quests ->
       "Lifepath Chosen", ending quests -> "Ending Reached", etc.).
    2. For each ``(internal_id, display_name)`` pair, look up the wire id in
       ``location_name_to_id``. Event locations (code=None) get dropped.
    """
    aliases = locations_mod.location_internal_id_to_display_name
    location_name_to_id = locations_mod.location_name_to_id

    result: Dict[str, int] = {}
    for internal_id, display_name in aliases.items():
        wire_id = location_name_to_id.get(display_name)
        if wire_id is None:
            continue
        result[internal_id] = wire_id
    return result


def build_item_mapping(items_mod) -> Dict[int, str]:
    """Return ``{archipelago_wire_id: in_game_ap_string}`` from items.py."""
    return dict(items_mod.item_id_to_game_id)


def _escape_reds_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace("\"", "\\\"")


REDS_HEADER = """// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
//
// Generated by worlds/cyberpunk2077/tools/generate_redscript_ap_mappings.py
// Source of truth: worlds/cyberpunk2077/locations.py, worlds/cyberpunk2077/items.py
// Regenerate via the repo wrapper: tools/build_cyberpunk2077_apworld.py
// Generated (UTC): {timestamp}
//
// ResolveLocationAddress(locationId: String) -> Int64
//   Maps an in-game check string (a location_table key, an alias such as a
//   lifepath/ending quest id, or an "ap_tarot_N" key) to the Archipelago
//   wire id. Returns -1 if the check has no mapping.
//
// ResolveItemId(itemId: Int64) -> String
//   Maps an Archipelago numeric item id from the native item queue to the
//   in-game "ap_*" identifier consumed by APItemParser / APGameSystem.
//   Returns an empty string when no mapping exists.
//
// GetAllLocationIds() -> array<String>
//   Returns every internal check string so the client can re-send all
//   previously-completed checks on connect/respawn (APGameSystem.SendSyncChecks).

module Archipelago

public class APArchipelagoIdMappings {{
"""


def _emit_location_resolver(location_map: Dict[str, int]) -> List[str]:
    items = sorted(location_map.items(), key=lambda kv: (kv[1], kv[0]))
    lines: List[str] = []
    lines.append("    public static func ResolveLocationAddress(locationId: String) -> Int64 {")
    lines.append("        if StrLen(locationId) == 0 { return -1l; }")
    for internal_id, wire_id in items:
        lines.append(
            f'        if StrCmp(locationId, "{_escape_reds_string(internal_id)}") == 0 {{ return {wire_id}l; }}'
        )
    lines.append("        return -1l;")
    lines.append("    }")
    return lines


def _emit_location_id_list(location_map: Dict[str, int]) -> List[str]:
    # Emit every internal check string so the client can re-send all
    # previously-completed checks on connect/respawn (see APGameSystem.SendSyncChecks).
    internal_ids = sorted(location_map.keys())
    lines: List[str] = []
    lines.append("    public static func GetAllLocationIds() -> array<String> {")
    lines.append("        let ids: array<String>;")
    for internal_id in internal_ids:
        lines.append(f'        ArrayPush(ids, "{_escape_reds_string(internal_id)}");')
    lines.append("        return ids;")
    lines.append("    }")
    return lines


def _emit_item_resolver(item_map: Dict[int, str]) -> List[str]:
    items = sorted(item_map.items(), key=lambda kv: kv[0])
    lines: List[str] = []
    lines.append("    public static func ResolveItemId(itemId: Int64) -> String {")
    for wire_id, in_game in items:
        lines.append(
            f'        if itemId == {wire_id}l {{ return "{_escape_reds_string(in_game)}"; }}'
        )
    lines.append('        return "";')
    lines.append("    }")
    return lines


def render(location_map: Dict[str, int], item_map: Dict[int, str]) -> str:
    timestamp = datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds")
    lines: List[str] = [REDS_HEADER.format(timestamp=timestamp)]
    lines.extend(_emit_location_resolver(location_map))
    lines.append("")
    lines.extend(_emit_location_id_list(location_map))
    lines.append("")
    lines.extend(_emit_item_resolver(item_map))
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def _resolve_default_output() -> Path:
    """Best-effort guess for the mod-repo's RedScript output path."""
    mod_root = os.environ.get("CYBERPUNK_MOD_ROOT")
    if mod_root:
        base = Path(mod_root)
    else:
        # Resolve junctions/symlinks so this works whether the script lives
        # under the mod-repo directly or under Archipelago/worlds/<symlink>.
        world_real = Path(os.path.realpath(WORLD_DIR))
        base = world_real.parent.parent  # .../worlds/cyberpunk2077 -> mod-root
    return (
        base
        / "Cyberpunk2077"
        / "r6"
        / "scripts"
        / "CyberPunkArchipelago"
        / "Cyberpunk2077_Archipelago_Client"
        / "APArchipelagoIdMappings.reds"
    )


def write_reds(output: Path, contents: str) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(contents, encoding="utf-8", newline="\n")


def main(argv: Iterable[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate APArchipelagoIdMappings.reds from the world data tables."
    )
    parser.add_argument(
        "--output",
        "-o",
        type=Path,
        default=None,
        help="Destination .reds file (defaults to the mod-repo RedScript path).",
    )
    parser.add_argument(
        "--print",
        action="store_true",
        dest="print_only",
        help="Render to stdout instead of writing to disk.",
    )
    args = parser.parse_args(list(argv) if argv is not None else None)

    locations_mod, items_mod = _load_world_modules()
    location_map = build_location_mapping(locations_mod)
    item_map = build_item_mapping(items_mod)
    rendered = render(location_map, item_map)

    if args.print_only:
        sys.stdout.write(rendered)
        return 0

    output = args.output or _resolve_default_output()
    write_reds(output, rendered)
    print(
        f"[gen_reds] wrote {output}  "
        f"(locations: {len(location_map)}, items: {len(item_map)})"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
