#!/usr/bin/env python3
"""
generate_tables.py
==================
Reads worlds/cyberpunk2077/items.py and locations.py WITHOUT importing the
full Archipelago framework and generates two C++ header files consumed by the
Red4EXT plugin:

    native/src/ItemMapping.hpp
        AP item ID (int64_t) → internal game string used by APItemParser

    native/src/LocationMapping.hpp
        location check string (what tcpClient.SendCheck sends) → AP location ID (int64_t)

Run from the repository root:
    python native/generate_tables.py
"""

import re
import sys
import os
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ITEMS_SRC  = REPO_ROOT / "worlds" / "cyberpunk2077" / "items.py"
LOCS_SRC   = REPO_ROOT / "worlds" / "cyberpunk2077" / "locations.py"
OUT_DIR    = REPO_ROOT / "native" / "src"

BASE_ID = 2077000


# ---------------------------------------------------------------------------
# Minimal stubs so the Python source files can be exec()'d in isolation
# ---------------------------------------------------------------------------

class _IntFlag(int):
    def __or__(self, other):  return _IntFlag(int(self) | int(other))
    def __ror__(self, other): return self.__or__(other)

class ItemClassification:
    progression    = _IntFlag(1)
    useful         = _IntFlag(2)
    filler         = _IntFlag(0)
    trap           = _IntFlag(4)
    skip_balancing = _IntFlag(8)
    deprioritized  = _IntFlag(16)

class LocationProgressType:
    DEFAULT  = 0
    PRIORITY = 1
    EXCLUDED = 2

class Item:
    game = ""

class Location:
    game = ""

# Stubs for BaseClasses imports
stubs = {
    "Item": Item,
    "Location": Location,
    "ItemClassification": ItemClassification,
    "LocationProgressType": LocationProgressType,
}

def _exec_module(path: Path, extra_globals: dict) -> dict:
    src = path.read_text(encoding="utf-8")
    # Patch away 'from BaseClasses import ...' lines
    src = re.sub(r"^from BaseClasses import .*$", "", src, flags=re.MULTILINE)
    src = re.sub(r"^import BaseClasses.*$",        "", src, flags=re.MULTILINE)
    globs = {**stubs, **extra_globals, "__builtins__": __builtins__}
    exec(compile(src, str(path), "exec"), globs)
    return globs


# ---------------------------------------------------------------------------
# Parse items
# ---------------------------------------------------------------------------

def parse_items():
    globs = _exec_module(ITEMS_SRC, {"__name__": "items"})
    item_table = globs["item_table"]
    item_id_to_game_id = globs["item_id_to_game_id"]
    return item_id_to_game_id        # Dict[int, str]  e.g. {2077000: "ap_dat_..."}


# ---------------------------------------------------------------------------
# Parse locations
# ---------------------------------------------------------------------------

def parse_locations():
    globs = _exec_module(LOCS_SRC, {"__name__": "locations"})
    location_table = globs["location_table"]

    # Replicate _assign_location_codes logic
    idx = 0
    mapping = {}   # internal_id_str → ap_location_id (int)
    for internal_id, data in location_table.items():
        if getattr(data, "category", None) == "event":
            continue
        ap_id = BASE_ID + idx
        mapping[internal_id] = ap_id
        idx += 1

    # Also include location_internal_id_to_display_name if present (multi-quest → one loc)
    loc_alias = globs.get("location_internal_id_to_display_name", {})
    # loc_alias maps quest_id → display_name; display_name is a key in location_table
    display_to_ap = {data.display_name if hasattr(data,'display_name') else k: v
                     for k, v in mapping.items() for _ in [1]}

    # Build a display_name → ap_id map first
    dn_to_ap = {}
    idx = 0
    for internal_id, data in location_table.items():
        if getattr(data, "category", None) == "event":
            continue
        dn_to_ap[data.display_name] = BASE_ID + idx
        idx += 1

    # Then alias entries point the extra quest IDs at the same AP ID
    for quest_id, display_name in loc_alias.items():
        if display_name in dn_to_ap:
            mapping[quest_id] = dn_to_ap[display_name]

    # Tarot cards: the game calls SendCheck with e.g. "tarot_0", "tarot_1" ...
    # Those come from APConstants.GetTarotCheckPrefix() + number.
    # They ARE in location_table already if present; nothing extra needed.

    return mapping   # Dict[str, int]  e.g. {"q001_intro": 2077002}


# ---------------------------------------------------------------------------
# Emit C++ headers
# ---------------------------------------------------------------------------

ITEM_HEADER_TMPL = """\
// AUTO-GENERATED by native/generate_tables.py — do not edit by hand.
// Re-run: python native/generate_tables.py
#pragma once
#include <cstdint>
#include <string_view>
#include <unordered_map>

namespace Archipelago {{

// Maps AP item ID → internal game item string (what APItemParser expects).
// BASE_ID = {base_id}, entries = {count}
inline const std::unordered_map<int64_t, std::string_view>& GetItemIdToGameId() {{
    static const std::unordered_map<int64_t, std::string_view> kTable = {{
{entries}
    }};
    return kTable;
}}

inline std::string_view LookupItemGameId(int64_t apItemId) {{
    const auto& t = GetItemIdToGameId();
    auto it = t.find(apItemId);
    return (it != t.end()) ? it->second : "";
}}

}} // namespace Archipelago
"""

LOCATION_HEADER_TMPL = """\
// AUTO-GENERATED by native/generate_tables.py — do not edit by hand.
// Re-run: python native/generate_tables.py
#pragma once
#include <cstdint>
#include <string_view>
#include <unordered_map>

namespace Archipelago {{

// Maps internal check string → AP location ID.
// Used by APBridge::SendCheck to call AP_SendItem with the correct integer ID.
// BASE_ID = {base_id}, entries = {count}
inline const std::unordered_map<std::string_view, int64_t>& GetLocationNameToId() {{
    static const std::unordered_map<std::string_view, int64_t> kTable = {{
{entries}
    }};
    return kTable;
}}

inline int64_t LookupLocationId(std::string_view checkName) {{
    const auto& t = GetLocationNameToId();
    auto it = t.find(checkName);
    return (it != t.end()) ? it->second : -1;
}}

}} // namespace Archipelago
"""

DISPLAY_ITEM_HEADER_TMPL = """\
// AUTO-GENERATED by native/generate_tables.py — do not edit by hand.
// Re-run: python native/generate_tables.py
#pragma once
#include <string_view>
#include <unordered_map>

namespace Archipelago {{

// Maps AP item *display* name (as sent in AP_ItemRecvMessage.item)
// to the internal game item string that APItemParser recognises.
// entries = {count}
inline const std::unordered_map<std::string_view, std::string_view>& GetDisplayNameToGameId() {{
    static const std::unordered_map<std::string_view, std::string_view> kTable = {{
{entries}
    }};
    return kTable;
}}

inline std::string_view LookupItemByDisplayName(std::string_view displayName) {{
    const auto& t = GetDisplayNameToGameId();
    auto it = t.find(displayName);
    return (it != t.end()) ? it->second : "";
}}

}} // namespace Archipelago
"""


def _escape_cpp_str(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def emit_item_mapping(item_id_to_game_id: dict, out_dir: Path):
    lines = []
    for ap_id in sorted(item_id_to_game_id):
        game_id = item_id_to_game_id[ap_id]
        lines.append(f'        {{ {ap_id}LL, "{_escape_cpp_str(game_id)}" }},')
    content = ITEM_HEADER_TMPL.format(
        base_id=BASE_ID,
        count=len(lines),
        entries="\n".join(lines),
    )
    out = out_dir / "ItemMapping.hpp"
    out.write_text(content, encoding="utf-8")
    print(f"  Wrote {out}  ({len(lines)} items)")


def emit_location_mapping(loc_map: dict, out_dir: Path):
    lines = []
    for name in sorted(loc_map):
        ap_id = loc_map[name]
        lines.append(f'        {{ "{_escape_cpp_str(name)}", {ap_id}LL }},')
    content = LOCATION_HEADER_TMPL.format(
        base_id=BASE_ID,
        count=len(lines),
        entries="\n".join(lines),
    )
    out = out_dir / "LocationMapping.hpp"
    out.write_text(content, encoding="utf-8")
    print(f"  Wrote {out}  ({len(lines)} locations)")


def emit_display_name_mapping(out_dir: Path):
    """
    Also generate a DisplayNameMapping.hpp from items.py so the plugin
    can translate AP_ItemRecvMessage.item (human name) → game string.
    """
    globs = _exec_module(ITEMS_SRC, {"__name__": "items"})
    item_table = globs["item_table"]

    lines = []
    for display_name, data in item_table.items():
        if data.code is None:
            continue
        lines.append(f'        {{ "{_escape_cpp_str(display_name)}", "{_escape_cpp_str(data.name)}" }},')

    content = DISPLAY_ITEM_HEADER_TMPL.format(
        count=len(lines),
        entries="\n".join(lines),
    )
    out = out_dir / "DisplayNameMapping.hpp"
    out.write_text(content, encoding="utf-8")
    print(f"  Wrote {out}  ({len(lines)} display-name entries)")


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    print("Generating C++ mapping tables...")

    item_id_to_game_id = parse_items()
    emit_item_mapping(item_id_to_game_id, OUT_DIR)

    loc_map = parse_locations()
    emit_location_mapping(loc_map, OUT_DIR)

    emit_display_name_mapping(OUT_DIR)

    print("Done.")


if __name__ == "__main__":
    main()
