AUTOTRACKER_ENABLE_ITEM_TRACKING = true
AUTOTRACKER_ENABLE_LOCATION_TRACKING = true
AUTOTRACKER_ENABLE_DEBUG_LOGGING = false
AUTOTRACKER_ENABLE_DEBUG_LOGGING_AP = false and AUTOTRACKER_ENABLE_DEBUG_LOGGING

require("scripts.autotracking.archipelago")
