// AUTO-GENERATED by native/generate_tables.py — do not edit by hand.
// Re-run: python native/generate_tables.py
#pragma once
#include <string_view>
#include <unordered_map>

namespace Archipelago {

// Maps AP item *display* name (as sent in AP_ItemRecvMessage.item)
// to the internal game item string that APItemParser recognises.
// entries = 71
inline const std::unordered_map<std::string_view, std::string_view>& GetDisplayNameToGameId() {
    static const std::unordered_map<std::string_view, std::string_view> kTable = {
        { "Westbrook Access Token", "ap_dat_westbrookAccessToken" },
        { "City Center Access Token", "ap_dat_cityCenterAccessToken" },
        { "Heywood Access Token", "ap_dat_heywoodAccessToken" },
        { "Santo Domingo Access Token", "ap_dat_santoDomingoAccessToken" },
        { "Pacifica Access Token", "ap_dat_pacificaAccessToken" },
        { "Dogtown Acccess Token", "ap_dat_dogtownAccessToken" },
        { "Badlands Access Token", "ap_dat_badlandsAccessToken" },
        { "Westbrook Japantown Access Token", "ap_dat_westbrookJapantownAccessToken" },
        { "Westbrook Charter Hill Access Token", "ap_dat_westbrookCharterHillAccessToken" },
        { "Westbrook North Oak Access Token", "ap_dat_westbrookNorthOakAccessToken" },
        { "City Center Corpo Plaza Access Token", "ap_dat_cityCenterCorpoPlazaAccessToken" },
        { "City Center Downtown Access Token", "ap_dat_cityCenterDowntownAccessToken" },
        { "Heywood Wellsprings Access Token", "ap_dat_heywoodWellspringsAccessToken" },
        { "Heywood The Glen Access Token", "ap_dat_heywoodTheGlenAccessToken" },
        { "Heywood Vista Del Rey Access Token", "ap_dat_heywoodVistaDelReyAccessToken" },
        { "Santo Domingo Arroyo Access Token", "ap_dat_santoDomingoArroyoAccessToken" },
        { "Santo Domingo Rancho Coronado Access Token", "ap_dat_santoDomingoRanchoCoronadoAccessToken" },
        { "Pacifica Coastview Access Token", "ap_dat_pacificaCoastviewAccessToken" },
        { "Pacifica West Wind Estate Access Token", "ap_dat_pacificaWestWindEstateAccessToken" },
        { "Badlands Biotechnica Flats Access Token", "ap_dat_badlandsBiotechnicaFlatsAccessToken" },
        { "Badlands Jackson Plains Access Token", "ap_dat_badlandsJacksonPlainsAccessToken" },
        { "Badlands Laguna Bend Access Token", "ap_dat_badlandsLagunaBendAccessToken" },
        { "Badlands Red Peaks Access Token", "ap_dat_badlandsRedPeaksAccessToken" },
        { "Badlands Rocky Ridge Access Token", "ap_dat_badlandsRockyRidgeAccessToken" },
        { "Badlands Sierra Sonora Access Token", "ap_dat_badlandsSierraSonoraAccessToken" },
        { "Badlands SoCal Badlands Access Token", "ap_dat_badlandsSoCalBadlandsAccessToken" },
        { "Badlands Yucca Access Token", "ap_dat_badlandsYuccaAccessToken" },
        { "Badlands Morro Rock Access Token", "ap_dat_badlandsMorroRockAccessToken" },
        { "5000 Eddies", "ap_ed_Items.money_5000" },
        { "Progressive Overheat Quickhack", "ap_prog_overheat" },
        { "Progressive Short Circuit Quickhack", "ap_prog_shortCircuit" },
        { "Progressive Contagion Quickhack", "ap_prog_contagion" },
        { "Progressive Synapse Burnout Quickhack", "ap_prog_synapseBurnout" },
        { "Progressive Cripple Movement Quickhack", "ap_prog_crippleMovement" },
        { "Progressive Weapon Glitch Quickhack", "ap_prog_weaponGlitch" },
        { "Progressive Ping Quickhack", "ap_prog_ping" },
        { "Progressive Bait Quickhack", "ap_prog_bait" },
        { "Progressive Request Backup Quickhack", "ap_prog_requestBackup" },
        { "Progressive Memory Wipe Quickhack", "ap_prog_memoryWipe" },
        { "Progressive Sonic Shock Quickhack", "ap_prog_sonicShock" },
        { "Progressive Cyberpsychosis Quickhack", "ap_prog_madness" },
        { "Progressive Suicide Quickhack", "ap_prog_suicide" },
        { "Progressive System Collapse Quickhack", "ap_prog_systemCollapse" },
        { "Progressive Detonate Grenade Quickhack", "ap_prog_grenadeExplode" },
        { "Progressive Reboot Optics Quickhack", "ap_prog_rebootOptics" },
        { "Progressive Cyberware Malfunction Quickhack", "ap_prog_cyberwareMalfunction" },
        { "Pistol Weapon Pass", "ap_wep_pistolPass" },
        { "SMG Weapon Pass", "ap_wep_smgPass" },
        { "Shotgun Weapon Pass", "ap_wep_shotgunPass" },
        { "Sniper Weapon Pass", "ap_wep_sniperPass" },
        { "LMG Weapon Pass", "ap_wep_lmgPass" },
        { "Rifle Weapon Pass", "ap_wep_riflePass" },
        { "Melee Weapon Pass", "ap_wep_meleePass" },
        { "Tier 1 Item Component", "ap_inv_Items.CommonMaterial1" },
        { "Tier 2 Item Component", "ap_inv_Items.UncommonMaterial1" },
        { "Tier 3 Item Component", "ap_inv_Items.RareMaterial1" },
        { "Tier 4 Item Component", "ap_inv_Items.EpicMaterial1" },
        { "Tier 5 Item Component", "ap_inv_Items.LegendaryMaterial1" },
        { "Tier 2 Quickhack Component", "ap_inv_Items.UncommonQuickhackMaterial1" },
        { "Tier 3 Quickhack Component", "ap_inv_Items.RareQuickhackMaterial1" },
        { "Tier 4 Quickhack Component", "ap_inv_Items.EpicQuickhackMaterial1" },
        { "Tier 5 Quickhack Component", "ap_inv_Items.LegendaryQuickhackMaterial1" },
        { "500 Eddies", "ap_ed_Items.money_500" },
        { "1000 Eddies", "ap_ed_Items.money_1000" },
        { "2500 Eddies", "ap_ed_Items.money_2500" },
        { "Ram Nugs", "ap_inv_Items.Blackmarket_MemoryBooster" },
        { "RAM Jolt", "ap_inv_Items.MemoryBooster" },
        { "Burrito XXXL", "ap_inv_Items.MediumQualityFood4" },
        { "NCPD False Cyberpsycho Report", "ap_trp_mostWanted" },
        { "Netrunner Virus", "ap_trp_randomDebuff" },
        { "Direct Alcohol Injection", "ap_trp_drunk" },
    };
    return kTable;
}

inline std::string_view LookupItemByDisplayName(std::string_view displayName) {
    const auto& t = GetDisplayNameToGameId();
    auto it = t.find(displayName);
    return (it != t.end()) ? it->second : "";
}

} // namespace Archipelago
