// AUTO-GENERATED by native/generate_tables.py — do not edit by hand.
// Re-run: python native/generate_tables.py
#pragma once
#include <cstdint>
#include <string_view>
#include <unordered_map>

namespace Archipelago {

// Maps AP item ID → internal game item string (what APItemParser expects).
// BASE_ID = 2077000, entries = 71
inline const std::unordered_map<int64_t, std::string_view>& GetItemIdToGameId() {
    static const std::unordered_map<int64_t, std::string_view> kTable = {
        { 2077000LL, "ap_dat_westbrookAccessToken" },
        { 2077001LL, "ap_dat_cityCenterAccessToken" },
        { 2077002LL, "ap_dat_heywoodAccessToken" },
        { 2077003LL, "ap_dat_santoDomingoAccessToken" },
        { 2077004LL, "ap_dat_pacificaAccessToken" },
        { 2077005LL, "ap_dat_dogtownAccessToken" },
        { 2077006LL, "ap_dat_badlandsAccessToken" },
        { 2077007LL, "ap_dat_westbrookJapantownAccessToken" },
        { 2077008LL, "ap_dat_westbrookCharterHillAccessToken" },
        { 2077009LL, "ap_dat_westbrookNorthOakAccessToken" },
        { 2077010LL, "ap_dat_cityCenterCorpoPlazaAccessToken" },
        { 2077011LL, "ap_dat_cityCenterDowntownAccessToken" },
        { 2077012LL, "ap_dat_heywoodWellspringsAccessToken" },
        { 2077013LL, "ap_dat_heywoodTheGlenAccessToken" },
        { 2077014LL, "ap_dat_heywoodVistaDelReyAccessToken" },
        { 2077015LL, "ap_dat_santoDomingoArroyoAccessToken" },
        { 2077016LL, "ap_dat_santoDomingoRanchoCoronadoAccessToken" },
        { 2077017LL, "ap_dat_pacificaCoastviewAccessToken" },
        { 2077018LL, "ap_dat_pacificaWestWindEstateAccessToken" },
        { 2077019LL, "ap_dat_badlandsBiotechnicaFlatsAccessToken" },
        { 2077020LL, "ap_dat_badlandsJacksonPlainsAccessToken" },
        { 2077021LL, "ap_dat_badlandsLagunaBendAccessToken" },
        { 2077022LL, "ap_dat_badlandsRedPeaksAccessToken" },
        { 2077023LL, "ap_dat_badlandsRockyRidgeAccessToken" },
        { 2077024LL, "ap_dat_badlandsSierraSonoraAccessToken" },
        { 2077025LL, "ap_dat_badlandsSoCalBadlandsAccessToken" },
        { 2077026LL, "ap_dat_badlandsYuccaAccessToken" },
        { 2077027LL, "ap_dat_badlandsMorroRockAccessToken" },
        { 2077028LL, "ap_ed_Items.money_5000" },
        { 2077029LL, "ap_prog_overheat" },
        { 2077030LL, "ap_prog_shortCircuit" },
        { 2077031LL, "ap_prog_contagion" },
        { 2077032LL, "ap_prog_synapseBurnout" },
        { 2077033LL, "ap_prog_crippleMovement" },
        { 2077034LL, "ap_prog_weaponGlitch" },
        { 2077035LL, "ap_prog_ping" },
        { 2077036LL, "ap_prog_bait" },
        { 2077037LL, "ap_prog_requestBackup" },
        { 2077038LL, "ap_prog_memoryWipe" },
        { 2077039LL, "ap_prog_sonicShock" },
        { 2077040LL, "ap_prog_madness" },
        { 2077041LL, "ap_prog_suicide" },
        { 2077042LL, "ap_prog_systemCollapse" },
        { 2077043LL, "ap_prog_grenadeExplode" },
        { 2077044LL, "ap_prog_rebootOptics" },
        { 2077045LL, "ap_prog_cyberwareMalfunction" },
        { 2077046LL, "ap_wep_pistolPass" },
        { 2077047LL, "ap_wep_smgPass" },
        { 2077048LL, "ap_wep_shotgunPass" },
        { 2077049LL, "ap_wep_sniperPass" },
        { 2077050LL, "ap_wep_lmgPass" },
        { 2077051LL, "ap_wep_riflePass" },
        { 2077052LL, "ap_wep_meleePass" },
        { 2077053LL, "ap_inv_Items.CommonMaterial1" },
        { 2077054LL, "ap_inv_Items.UncommonMaterial1" },
        { 2077055LL, "ap_inv_Items.RareMaterial1" },
        { 2077056LL, "ap_inv_Items.EpicMaterial1" },
        { 2077057LL, "ap_inv_Items.LegendaryMaterial1" },
        { 2077058LL, "ap_inv_Items.UncommonQuickhackMaterial1" },
        { 2077059LL, "ap_inv_Items.RareQuickhackMaterial1" },
        { 2077060LL, "ap_inv_Items.EpicQuickhackMaterial1" },
        { 2077061LL, "ap_inv_Items.LegendaryQuickhackMaterial1" },
        { 2077062LL, "ap_ed_Items.money_500" },
        { 2077063LL, "ap_ed_Items.money_1000" },
        { 2077064LL, "ap_ed_Items.money_2500" },
        { 2077065LL, "ap_inv_Items.Blackmarket_MemoryBooster" },
        { 2077066LL, "ap_inv_Items.MemoryBooster" },
        { 2077067LL, "ap_inv_Items.MediumQualityFood4" },
        { 2077068LL, "ap_trp_mostWanted" },
        { 2077069LL, "ap_trp_randomDebuff" },
        { 2077070LL, "ap_trp_drunk" },
    };
    return kTable;
}

inline std::string_view LookupItemGameId(int64_t apItemId) {
    const auto& t = GetItemIdToGameId();
    auto it = t.find(apItemId);
    return (it != t.end()) ? it->second : "";
}

} // namespace Archipelago
